**1. Import numpy as np and see the version**

In [0]:
import numpy as np
print(np.__version__)

**2. How to create a 1D array?**

Desired Output : - array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr = np.arange(10)
arr

**3. Create a 3×3 numpy array of all True’s**

In [0]:
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**4. Extract all odd numbers from array**

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

**5. Replace all odd numbers in arr with -1**

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

**6. Replace all odd numbers in arr with -1 without changing arr**

Input : arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Output : array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [0]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

**7. Convert a 1D array to a 2D array with 2 rows**

Input : np.arange(10)

Output : array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9]])

In [0]:
arr = np.arange(10)
arr.reshape(2, -1) 

**8. Stack arrays a and b vertically**

Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

 array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

**9. Stack the arrays a and b horizontally.**

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [0]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

**10. Create the following pattern without hardcoding. Use only numpy functions and the below input array a**

Input:

a = np.array([1,2,3])`

Output:

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [0]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

**11. Get the common items between a and b**

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

array([2, 4])

In [0]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

**12. From array a remove all items present in array b **
Input:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

Desired Output:

array([1,2,3,4])

In [0]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# From 'a' remove all of 'b'
np.setdiff1d(a,b)

**13. Get the positions where elements of a and b match**
Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

(array([1, 3, 5, 7]),)

In [0]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

**14. Get all items between 5 and 10 from a.**

Input:

a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:

(array([6, 9, 10]),)

In [0]:
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]
#> (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

**15. Reverse the rows of a 2D array arr.**

Input

arr = np.arange(9).reshape(3,3)


In [0]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[::-1]

**16 Reverse the columns of a 2D array arr.**

Input
arr = np.arange(9).reshape(3,3)

In [0]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**16 . Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.**

In [0]:
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
# print(rand_arr)

# Solution Method 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

https://www.machinelearningplus.com/python/101-numpy-exercises-python/